### ISSUE TITLE
install pointnet2_ops_lib and Chamfer Distance

### ISSUE THREAD

**Issue by hldbalabala** [corecai163/ODGNet#7]
Can I install pointnet2_ops_lib and Chamfer Distance without using an extension, but instead install them through pip? 
What are their respective versions?

**Comment by corecai163** [comment]
Hi,
It seems unlikely that the pointnet2_pos_lib can be installed using pip, as I couldn’t find any existing prebuilt pip package for it. However, for Chamfer distance, I believe the PyTorch3D package provides implementations. [pytorch3d.loss](https://pytorch3d.readthedocs.io/en/latest/modules/loss.html)

**Comment by hldbalabala** [comment]
Thank you!!
